"""
Thermal_detector.py

Very simple thermal UAV detector based on Method 1:

    "Detect objects that are locally brighter than their surrounding background."

This file handles only the detection algorithm.

It does NOT handle:
    - video reading
    - live display
    - multithreading
    - video recording

Main function:

    boxes = detect_frame(frame, algorithm_config)

Optional debug function:

    debug_images = get_last_debug_images()

The live-stream script can use the debug images to show:
    - original frame
    - blurred local background
    - subtracted local contrast image
    - annotated detection result
"""

from dataclasses import dataclass
import cv2
import numpy as np


# -------------------------------------------------------------------------
# Output box structure
# -------------------------------------------------------------------------

@dataclass
class Box:
    """
    Single detection box.

    bbox:
        (x, y, w, h)

    label:
        Display label.

    score:
        Simple confidence-like score.
        Here it is based on local contrast, not a neural-network probability.
    """
    bbox: tuple
    label: str
    score: float


# -------------------------------------------------------------------------
# Internal debug image storage
# -------------------------------------------------------------------------
# The live script can read these using get_last_debug_images().
# This avoids changing the detector output format.
# detect_frame() still returns only boxes.

_LAST_DEBUG_IMAGES = {
    "original": None,
    "blurred": None,
    "subtracted": None,
    "mask": None,
}


def get_last_debug_images():
    """
    Return the latest debug images generated by detect_frame().

    Returns:
        dict with keys:
            original
            blurred
            subtracted
            mask
    """
    return _LAST_DEBUG_IMAGES


# -------------------------------------------------------------------------
# Utility functions
# -------------------------------------------------------------------------

def _get_config_value(config, key, default):
    """
    Safely read a value from algorithm_config.

    This supports both:
        dict-style config:
            config["blur_sigma"]

        SimpleNamespace-style config:
            config.blur_sigma
    """
    if isinstance(config, dict):
        return config.get(key, default)

    return getattr(config, key, default)


def _to_gray(frame):
    """
    Convert input frame to grayscale.

    Thermal frames are often visually grayscale, but OpenCV may still provide
    them as BGR images. This function handles both cases.
    """
    if frame is None:
        raise ValueError("Input frame is None.")

    if len(frame.shape) == 2:
        return frame.copy()

    if len(frame.shape) == 3:
        return cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    raise ValueError(f"Unsupported frame shape: {frame.shape}")


def _normalize_for_display(image):
    """
    Convert an image to display-friendly uint8.

    The subtraction image may have a small intensity range.
    Normalizing it makes it easier to visually inspect.
    """
    if image is None:
        return None

    image = image.astype(np.float32)

    min_val = float(np.min(image))
    max_val = float(np.max(image))

    if max_val - min_val < 1e-6:
        return np.zeros_like(image, dtype=np.uint8)

    normalized = 255.0 * (image - min_val) / (max_val - min_val)
    return normalized.astype(np.uint8)


def _filter_candidate(x, y, w, h, area, gray, diff, config):
    """
    Decide whether a contour is a valid UAV candidate.

    Filtering is intentionally simple:
        - reject too-small noise
        - reject huge background regions
        - reject weirdly large boxes
        - require enough local contrast inside the box
    """
    min_area = _get_config_value(config, "min_area", 2)
    max_area = _get_config_value(config, "max_area", 3000)

    min_width = _get_config_value(config, "min_width", 2)
    min_height = _get_config_value(config, "min_height", 2)

    max_width = _get_config_value(config, "max_width", 250)
    max_height = _get_config_value(config, "max_height", 250)

    min_mean_diff = _get_config_value(config, "min_mean_diff", 5.0)
    min_max_diff = _get_config_value(config, "min_max_diff", 15.0)

    if area < min_area:
        return False, 0.0

    if area > max_area:
        return False, 0.0

    if w < min_width or h < min_height:
        return False, 0.0

    if w > max_width or h > max_height:
        return False, 0.0

    roi_diff = diff[y:y + h, x:x + w]

    if roi_diff.size == 0:
        return False, 0.0

    mean_diff = float(np.mean(roi_diff))
    max_diff = float(np.max(roi_diff))

    if mean_diff < min_mean_diff and max_diff < min_max_diff:
        return False, 0.0

    # Simple score. This is not a probability.
    score = 0.5 * mean_diff + 0.5 * max_diff

    return True, score


def _merge_nearby_boxes(boxes, merge_distance_px):
    """
    Merge nearby boxes.

    This helps when the close UAV appears as several hot blobs:
        - motor 1
        - motor 2
        - motor 3
        - motor 4
        - body highlight

    The idea:
        Expand each box by merge_distance_px.
        If expanded boxes overlap, merge them.
    """
    if not boxes:
        return []

    merged = []

    for box in boxes:
        x, y, w, h, score = box

        current = [x, y, x + w, y + h, score]

        did_merge = False

        for existing in merged:
            ex1, ey1, ex2, ey2, escore = existing

            # Expanded current box
            cx1 = current[0] - merge_distance_px
            cy1 = current[1] - merge_distance_px
            cx2 = current[2] + merge_distance_px
            cy2 = current[3] + merge_distance_px

            # Expanded existing box
            ex1_exp = ex1 - merge_distance_px
            ey1_exp = ey1 - merge_distance_px
            ex2_exp = ex2 + merge_distance_px
            ey2_exp = ey2 + merge_distance_px

            overlap = not (
                cx2 < ex1_exp or
                cx1 > ex2_exp or
                cy2 < ey1_exp or
                cy1 > ey2_exp
            )

            if overlap:
                existing[0] = min(ex1, current[0])
                existing[1] = min(ey1, current[1])
                existing[2] = max(ex2, current[2])
                existing[3] = max(ey2, current[3])
                existing[4] = max(escore, score)
                did_merge = True
                break

        if not did_merge:
            merged.append(current)

    # Convert [x1, y1, x2, y2, score] back to [x, y, w, h, score]
    output = []

    for x1, y1, x2, y2, score in merged:
        output.append((x1, y1, x2 - x1, y2 - y1, score))

    return output


# -------------------------------------------------------------------------
# Main detection function
# -------------------------------------------------------------------------

def detect_frame(frame, algorithm_config):
    """
    Detect UAV candidates in one thermal frame.

    Method 1 step-by-step:

        1. Convert frame to grayscale.
        2. Blur the grayscale image to estimate local background.
        3. Subtract blurred background from original grayscale image.
        4. Threshold the local contrast image.
        5. Clean the binary mask using morphology.
        6. Find contours.
        7. Filter bad candidates.
        8. Merge nearby hot blobs.
        9. Return Box objects.

    Args:
        frame:
            OpenCV image.

        algorithm_config:
            Dictionary loaded from JSON under "algorithm".

    Returns:
        List[Box]
    """

    # ---------------------------------------------------------------------
    # Step 1: Convert thermal frame to grayscale
    # ---------------------------------------------------------------------
    gray = _to_gray(frame)

    # Optional denoising before background subtraction.
    # This reduces tiny sensor noise without destroying the UAV too much.
    pre_blur_kernel = _get_config_value(algorithm_config, "pre_blur_kernel", 3)

    if pre_blur_kernel > 1:
        if pre_blur_kernel % 2 == 0:
            pre_blur_kernel += 1

        gray_for_detection = cv2.GaussianBlur(
            gray,
            (pre_blur_kernel, pre_blur_kernel),
            0,
        )
    else:
        gray_for_detection = gray.copy()

    # ---------------------------------------------------------------------
    # Step 2: Estimate local background using strong Gaussian blur
    # ---------------------------------------------------------------------
    # Important:
    # The blur should be large enough that the UAV mostly disappears from
    # the background estimate, while trees/sky remain as smooth background.
    blur_sigma = _get_config_value(algorithm_config, "blur_sigma", 15.0)

    background = cv2.GaussianBlur(
        gray_for_detection,
        (0, 0),
        sigmaX=blur_sigma,
        sigmaY=blur_sigma,
    )

    # ---------------------------------------------------------------------
    # Step 3: Subtract local background from original image
    # ---------------------------------------------------------------------
    # Bright UAV parts become high.
    # Uniform sky/tree background becomes low.
    diff = cv2.subtract(gray_for_detection, background)

    # Optional contrast normalization for detection.
    # Usually keep this False first, because raw diff is easier to tune.
    normalize_diff_for_detection = _get_config_value(
        algorithm_config,
        "normalize_diff_for_detection",
        False,
    )

    if normalize_diff_for_detection:
        diff_for_threshold = _normalize_for_display(diff)
    else:
        diff_for_threshold = diff

    # ---------------------------------------------------------------------
    # Step 4: Threshold local contrast image
    # ---------------------------------------------------------------------
    # This threshold means:
    #     "how much brighter than nearby background?"
    #
    # It does NOT mean:
    #     "how white in the whole image?"
    local_contrast_threshold = _get_config_value(
        algorithm_config,
        "local_contrast_threshold",
        20,
    )

    _, mask = cv2.threshold(
        diff_for_threshold,
        local_contrast_threshold,
        255,
        cv2.THRESH_BINARY,
    )

    # ---------------------------------------------------------------------
    # Step 5: Clean mask using morphology
    # ---------------------------------------------------------------------
    # Opening removes isolated noise.
    # Dilation helps connect nearby motor/body highlights.
    morph_kernel_size = _get_config_value(algorithm_config, "morph_kernel_size", 3)
    dilate_iterations = _get_config_value(algorithm_config, "dilate_iterations", 1)

    if morph_kernel_size > 1:
        if morph_kernel_size % 2 == 0:
            morph_kernel_size += 1

        kernel = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE,
            (morph_kernel_size, morph_kernel_size),
        )

        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

        if dilate_iterations > 0:
            mask = cv2.dilate(mask, kernel, iterations=dilate_iterations)

    # ---------------------------------------------------------------------
    # Step 6: Find contours in the cleaned mask
    # ---------------------------------------------------------------------
    contours, _ = cv2.findContours(
        mask,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE,
    )

    # ---------------------------------------------------------------------
    # Step 7: Filter contour candidates
    # ---------------------------------------------------------------------
    raw_boxes = []

    for contour in contours:
        area = cv2.contourArea(contour)
        x, y, w, h = cv2.boundingRect(contour)

        accepted, score = _filter_candidate(
            x=x,
            y=y,
            w=w,
            h=h,
            area=area,
            gray=gray,
            diff=diff,
            config=algorithm_config,
        )

        if accepted:
            raw_boxes.append((x, y, w, h, score))

    # ---------------------------------------------------------------------
    # Step 8: Merge nearby boxes
    # ---------------------------------------------------------------------
    # This is useful when close UAV motors are separated into several dots.
    merge_distance_px = _get_config_value(
        algorithm_config,
        "merge_distance_px",
        30,
    )

    merged_boxes = _merge_nearby_boxes(raw_boxes, merge_distance_px)

    # ---------------------------------------------------------------------
    # Step 9: Convert to Box objects
    # ---------------------------------------------------------------------
    boxes = []

    for x, y, w, h, score in merged_boxes:
        boxes.append(
            Box(
                bbox=(int(x), int(y), int(w), int(h)),
                label="thermal-uav",
                score=float(score),
            )
        )

    # ---------------------------------------------------------------------
    # Store debug images for live display
    # ---------------------------------------------------------------------
    _LAST_DEBUG_IMAGES["original"] = gray.copy()
    _LAST_DEBUG_IMAGES["blurred"] = background.copy()
    _LAST_DEBUG_IMAGES["subtracted"] = _normalize_for_display(diff)
    _LAST_DEBUG_IMAGES["mask"] = mask.copy()

    return boxes